/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Vehiculo;
import controlador.ControladorAuto;
import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author DUOC
 */
public class Menuvista extends javax.swing.JFrame {
     fondopanel fondo= new fondopanel();
     private ImageIcon imagen;
private Icon icono;

    /**
     * Creates new form Menuvista
     */
    public Menuvista() {
           this.setContentPane(fondo);
        initComponents();
         this.setLocationRelativeTo(this);
        //declarar la foto
        this.imagenicono(this.lbl_auto, "src/vista/mzda.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulomenu = new javax.swing.JLabel();
        lbl_patentemenu = new javax.swing.JLabel();
        lbl_preciomenu = new javax.swing.JLabel();
        lbl_aniomenu = new javax.swing.JLabel();
        cbo_marcamenu = new javax.swing.JComboBox<>();
        lbl_marcamenu = new javax.swing.JLabel();
        chk_nuevomenu = new javax.swing.JCheckBox();
        lbl_vehiculosalmacenados = new javax.swing.JLabel();
        btn_almacenar = new javax.swing.JButton();
        txt_patentemenu = new javax.swing.JTextField();
        txt_aniomenu = new javax.swing.JTextField();
        txt_preciomenu = new javax.swing.JTextField();
        lbl_nuevo = new javax.swing.JLabel();
        lbl_auto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mni_lista = new javax.swing.JMenuItem();
        mni_salir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulomenu.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        lbl_titulomenu.setText("PROYECTO AUTOMOTORA");

        lbl_patentemenu.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        lbl_patentemenu.setText("PATENTE:");

        lbl_preciomenu.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        lbl_preciomenu.setText("PRECIO:");

        lbl_aniomenu.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        lbl_aniomenu.setText("AÑO FABRICACIÓN:");

        cbo_marcamenu.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        cbo_marcamenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Marca-", "TOYOTA", "CHEVROLET", "NISSAN", "KIA", "SUBARU", "AUDI" }));
        cbo_marcamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_marcamenuActionPerformed(evt);
            }
        });

        lbl_marcamenu.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        lbl_marcamenu.setText("MARCA:");

        chk_nuevomenu.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        chk_nuevomenu.setText("NUEVO:");
        chk_nuevomenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lbl_vehiculosalmacenados.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        lbl_vehiculosalmacenados.setText("VEHICULOS ALMACENADOS: ");

        btn_almacenar.setFont(new java.awt.Font("Artifakt Element Black", 3, 12)); // NOI18N
        btn_almacenar.setText("ALMACENAR");
        btn_almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_almacenarActionPerformed(evt);
            }
        });

        txt_patentemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_patentemenuActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        mni_lista.setText("Listar vehiculos");
        mni_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_listaActionPerformed(evt);
            }
        });
        jMenu1.add(mni_lista);

        jMenuBar1.add(jMenu1);

        mni_salir.setText("Salir");

        jMenuItem2.setText("Cerrar aplicación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mni_salir.add(jMenuItem2);

        jMenuBar1.add(mni_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_nuevomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(lbl_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_patentemenu)
                                    .addComponent(lbl_marcamenu)
                                    .addComponent(lbl_aniomenu)
                                    .addComponent(lbl_preciomenu))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbo_marcamenu, 0, 125, Short.MAX_VALUE)
                                    .addComponent(txt_aniomenu)
                                    .addComponent(txt_preciomenu)
                                    .addComponent(txt_patentemenu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(lbl_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lbl_titulomenu)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_vehiculosalmacenados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulomenu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_patentemenu)
                            .addComponent(txt_patentemenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_marcamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_marcamenu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_aniomenu)
                            .addComponent(txt_aniomenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_preciomenu)
                            .addComponent(txt_preciomenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(chk_nuevomenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lbl_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_vehiculosalmacenados, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_marcamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_marcamenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_marcamenuActionPerformed

    private void txt_patentemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_patentemenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_patentemenuActionPerformed

    private void btn_almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_almacenarActionPerformed
       int vehiculovacio=0;
         lbl_vehiculosalmacenados.setText(""+vehiculovacio+1);
        String patente = txt_patentemenu.getText();
        int anio_fabricacion = Integer.parseInt(txt_aniomenu.getText());
        int precio = Integer.parseInt(txt_preciomenu.getText());
         String marca = cbo_marcamenu.getSelectedItem().toString();
        lbl_marcamenu.setText(marca);
        // chk_checkbox.isSelected();
        if(chk_nuevomenu.isSelected())
        {
            lbl_nuevo.setText("El Vehiculo es nuevo");
        }
        else
        {
            lbl_nuevo.setText("El vehiculo no es nuevo");
        }
        
        
        
        
        Vehiculo vehiculonuevo= new Vehiculo(patente, patente, anio_fabricacion, precio, rootPaneCheckingEnabled);
         ControladorAuto cu = new ControladorAuto();
        
        cu.agregarVehiculo(vehiculonuevo);
        JOptionPane.showMessageDialog(this,"Su vehiculo\n"+ "patente: "+patente+"\n marca:"+marca+"\n fue  registrado");
        
    }//GEN-LAST:event_btn_almacenarActionPerformed

    private void mni_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_listaActionPerformed
      Listavehiculo lv= new Listavehiculo();
      lv.setVisible(true);
      
      
    }//GEN-LAST:event_mni_listaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuvista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuvista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuvista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuvista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuvista().setVisible(true);
            }
        });
    }

       private void imagenicono(JLabel lbl, String ruta)
{
    this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_almacenar;
    private javax.swing.JComboBox<String> cbo_marcamenu;
    private javax.swing.JCheckBox chk_nuevomenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbl_aniomenu;
    private javax.swing.JLabel lbl_auto;
    private javax.swing.JLabel lbl_marcamenu;
    private javax.swing.JLabel lbl_nuevo;
    private javax.swing.JLabel lbl_patentemenu;
    private javax.swing.JLabel lbl_preciomenu;
    private javax.swing.JLabel lbl_titulomenu;
    private javax.swing.JLabel lbl_vehiculosalmacenados;
    private javax.swing.JMenuItem mni_lista;
    private javax.swing.JMenu mni_salir;
    private javax.swing.JTextField txt_aniomenu;
    private javax.swing.JTextField txt_patentemenu;
    private javax.swing.JTextField txt_preciomenu;
    // End of variables declaration//GEN-END:variables

class fondopanel extends JPanel
    {
        private Image fondoimagen;
        
        @Override
        public void paint(Graphics g)
        {
            fondoimagen = new ImageIcon(getClass().getResource("/imagen/degradadoverdefondo.jpg")).getImage();
            
            g.drawImage(fondoimagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }


}
